#!/bin/sh
WS=$(git config --get-color color.diff.whitespace "blue reverse")
RESET=$(git config --get-color "" "reset")
echo "${WS}your whitespace color or blue reverse${RESET}"
; HTTP
[http]
	sslVerify
[http "https://home.purehub.ga"]
	sslVerify = false
	cookieFile = /tmp/cookie.txt
